### ISSUE TITLE
Doesn't work on Intellij 2016.3

### ISSUE THREAD

**Issue by atomsfat** [vhakulinen/neovim-intellij-complete#10]
My IDE just updated and now I'm getting this error :

```bash
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "prefix" (class com.neovim.ApiInfo$Id), not marked as ignorable (one known property: "id"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.neovim.ApiInfoHolder["apiInfo"]->com.neovim.ApiInfo["types"]->java.util.LinkedHashMap["Buffer"]->com.neovim.Id["prefix"])
java.util.concurrent.CompletionException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "prefix" (class com.neovim.ApiInfo$Id), not marked as ignorable (one known property: "id"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.neovim.ApiInfoHolder["apiInfo"]->com.neovim.ApiInfo["types"]->java.util.LinkedHashMap["Buffer"]->com.neovim.Id["prefix"])
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.neovim.msgpack.RequestCallback.setResult(RequestCallback.java:24)
	at com.neovim.msgpack.MessagePackRPC.parseResponse(MessagePackRPC.java:249)
	at com.neovim.msgpack.MessagePackRPC.parsePacket(MessagePackRPC.java:202)
	at com.neovim.msgpack.MessagePackRPC.readFromInput(MessagePackRPC.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "prefix" (class com.neovim.ApiInfo$Id), not marked as ignorable (one known property: "id"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.neovim.ApiInfoHolder["apiInfo"]->com.neovim.ApiInfo["types"]->java.util.LinkedHashMap["Buffer"]->com.neovim.Id["prefix"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1083)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanAsArrayDeserializer.deserialize(BeanAsArrayDeserializer.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3760)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2108)
	at com.neovim.msgpack.RequestCallback.lambda$new$0(RequestCallback.java:17)
	at com.neovim.msgpack.RequestCallback.setResult(RequestCallback.java:22)
```

**Comment by mjtorn** [comment]
I'm kinda new to IntelliJ and wanted to try this as well. Found this issue and a list of old releases at http://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases

Tried with the community versions.

`15.0.6` was completely broken, the one that goes also by `143.2370.31`, and the next one `2016.1.4` aka `145.2070.6` complained:

    [  17339]  ERROR - llij.ide.plugins.PluginManager - com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "prefix" (class com.neovim.ApiInfo$Id), not marked as ignorable (one known property: "id"])

Tested with the latest trial version as well, and it still dies :(

Any clues as to why?

Thanks!

**Comment by ollieh** [comment]
I am also experiencing the same issue as @mjtorn , on intellij 2016.1.4. Judging from when this project was started and release dates of intellij, it looks like 2016.1.1 might work, but I can't find a download link.

**Comment by vhakulinen** [comment]
Hi, thanks for the input for this bug. Sadly, I don't have personal interest to spend my free time on this project anymore for time being.

Either way, the bug might come from neovim (ApiInfo). The library this project uses to talk to neovim is somewhat immature, in sense that it's development had been stalled even before I started this project. I suggest that you try some older version of neovim, that might fix the problem or not. Even if it does, its not really a fix, just a work around.

**Comment by Khalian** [comment]
Reproed on IntelliJ 2017. https://github.com/vhakulinen/neovim-intellij-complete/issues/13
